# config for analysis

# most CPUs to ever use at once
max_cpus: 12

# processed ccs files
processed_ccs: data/processed_ccs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv
rt_barcode_runs: data/rt_barcode_runs.csv

# adk44 script to convert sequences from R2 to R1
R2_to_R1: R2_to_R1.py

# amplicons sequenced by PacBio
amplicons: data/PacBio_amplicons.gb

# how to parse the amplicon
feature_parse_specs: data/feature_parse_specs.yaml

# the primary target for which we are calling mutations
primary_target: nucleocapsid

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGAGAGGGGCGGNATCCGCGGCCGC
  downstream: TTAACGTGGCTTCTTCTGCCACAGCATGATGAGAATAATAAGGGAAATGATAG
  minq: 20
  upstream_mismatch: 10
  downstream_mismatch: 10

# Parameters used when computed escape scores:
escape_score_type: frac_escape  # type of escape score, see dms_variants
escape_score_pseudocount: 0.5  # added to observed counts
escape_score_floor_E: 0  # floor on escape fractions
escape_score_ceil_E: 1  # ceiling on escape fractions
# Group variants by this when calculating escape scores; sensible values are
# "barcode" (to calculate a score for each barcoded variant) or
# "aa_substitutions" (to group all variants with same amino-acid substitutions):
escape_score_group_by: barcode
# How to group variants for homologs:
escape_score_homolog_group_by: aa_substitutions
# Filter variants (after grouping according to `escape_group_by`) with
# pre-selection counts < this quantile of stop codon variants, thereby
# removing low count "noise":
escape_score_stop_quantile_filter: 0.99
# Filter variants with ACE2-binding scores < this threshold, which is
# determined from the deep mutational scan (Starr et al, 2020):
escape_score_min_bind: -2.35
# Filter variants with expression < this threshold, which separates the
# two modes of expression in the deep mutational scan (Starr et al, 2020):
escape_score_min_expr: -1.5
# **Prior to fitting global epistasis models**, remove variants that have
# substitutions that are not observed in at least this many variants in a
# single-mutant **and** any context:
global_epistasis_filter_by_subs_observed_single: 0
global_epistasis_filter_by_subs_observed_any: 2
# Only retain mutation-level escape fraction estimates when there are
# **either** >= the indicated number of filtered variants (after grouping
# according to `escape_group_by`) with the mutation as a single mutant
# or in any context:
escape_frac_min_single_mut_measurements: 1
escape_frac_min_any_mut_measurements: 2

# Parameters in escape frac output file that enable dms-view
# visualization on PDB 6m0j:
escape_frac_protein_chain: E  # use this chain
escape_frac_protein_site_offset: 330  # add this to sequential sites

# Site- and mutation-level metrics for escape profiles
site_metric: site_total_escape_frac_epistasis_model
mut_metric: mut_escape_frac_epistasis_model
# Specify how to plot escape profiles
escape_profiles_config: data/escape_profiles_config.yaml
# Site color schemes for escape profiles
site_color_schemes: data/site_color_schemes.csv


# output directories / files
variants_dir: results/variants
figs_dir: results/figs
summary_dir: results/summary
codon_variant_table: results/prior_DMS_data/codon_variant_table.csv
counts_dir: results/counts
variant_counts: results/counts/variant_counts.csv
nt_variant_table_file: results/variants/nucleotide_variant_table.csv
escape_scores_dir: results/escape_scores
escape_score_samples: results/escape_scores/samples.csv
escape_scores: results/escape_scores/scores.csv
escape_fracs: results/escape_scores/escape_fracs.csv

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001
